// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cywmcspgkeqstgvjcdhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5d21jc3Bna2Vxc3RndmpjZGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDY4NzcsImV4cCI6MjA3NDM4Mjg3N30.pFZR3ewrtk0trmxUvIe2uDNJoFwCcXCrJYwn4mCfM-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});