// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwhtjcextjmumvrjyzil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3aHRqY2V4dGptdW12cmp5emlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODM3ODIsImV4cCI6MjA3MTI1OTc4Mn0.xQYsveHGhM6CmCKBElZA_x2gEOVd7o9l6lqnpS_JUjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});